default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('account') }}"
      database: DEMO_DBT
      password: "{{ env_var('dbt_password') }}"
      role: dbt_DEV_ROLE
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: "{{ env_var('dbt_user') }}"
      warehouse: dbt_DEV_WH
  target: dev

